### ISSUE TITLE
[Bug]: ProImageEditor got incompatible with PDF

### ISSUE THREAD

**Issue by saif-ellafi** [hm21/pro_image_editor#312]
### Package Version

7.0.0

### Flutter Version

3.27.1

### Platforms

Android, iOS, Web, Windows, macOS, Linux

### How to reproduce?

Hello,
I can't seem to upgrade to the latest build, unfortunately, something changed in the dependencies that now the package conflicts with another popular package: `pdf` https://pub.dev/packages/pdf

I bet dependencies are a pain, but there seems to be a hard lock here:

```
Because every version of pro_image_editor from git depends on image ^4.5.2 which depends on archive ^4.0.2, every version of pro_image_editor from git requires archive ^4.0.2.
And because pdf >=3.11.1 depends on archive ^3.4.0, pro_image_editor from git is incompatible with pdf >=3.11.1.
So, because pum depends on both pdf >=3.11.1 and pro_image_editor from git, version solving failed.
```

Best regards

**Comment by hm21** [comment]
Hey @saif-ellafi, 

The issue is that the `pdf` package depends on `archive: ^3.4.0`, which is an outdated version of the package. On the other hand, the `pro_image_editor` package depends on the `image` package, which requires the latest version of `archive: ^4.0.2`.

To temporarily resolve this conflict until the `pdf` package is updated to the latest version, you can override the `archive` dependency in your `pubspec.yaml` file as shown below:

```yaml
dependencies:
  flutter:
    sdk: flutter

  pro_image_editor:
    path: ../
    
  pdf: ^3.11.1
   
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# add the code below 
dependency_overrides: 
  archive: ^3.4.0
```

Don't forget to run `flutter clean` and `flutter pub get` if it doesn't work directly.
